# Use postgres/example user/password credentials


services:

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    volumes:
      - ./src/main/resources/:/docker-entrypoint-initdb.d/
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5439:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

